### ISSUE TITLE
migrate the tutorial to LLVM 6.0 (and -fsanitize=fuzzer)

### ISSUE THREAD

**Issue by kcc** [google/fuzzer-test-suite#111]
* update the docs
* update the get_clang script
* start using -fsanitize=fuzzer by default
* don't build libFuzzer from source (by default, and in the tutorial docs)
* rebuild the tutorial docker files (once everything else is done, I'll do that)

**Comment by morehouse** [comment]
@kcc: Last step is to rebuild the tutorial docker image and upload.

**Comment by kcc** [comment]
docker images updated. 
thanks!
