### ISSUE TITLE
add crash inputs for openthread

### ISSUE THREAD

**Issue by kcc** [google/fuzzer-test-suite#127]
openthread had a few stack-buffer-overflows in the past. 
Please add all crash inputs and document which revisions are required to trigger the crashes.

**Comment by morehouse** [comment]
Where are the stack-buffer-overflows?  I don't see any at https://oss-fuzz.com/testcases?project=openthread.

**Comment by morehouse** [comment]
Never mind, found them at https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=label%3AProj-openthread.
