### ISSUE TITLE
main() function

### ISSUE THREAD

**Issue by fwsGonzo** [google/fuzzer-test-suite#129]
After reviewing this fuzzer, I'm not sure I can use it. I can't initialize my program without a function that is run after global constructors. So I need libfuzzer to provide me a weak function I can override that will be a second main to fuzzer but a primary main to me. I don't care about program arguments. Again, I need to run a main-like function after global constructors, otherwise it's all up to random chance.
How is this solved?

Second issue: No tutorial or documentation mentions that int main() is already provided.

**Comment by Dor1s** [comment]
Doesn't http://llvm.org/docs/LibFuzzer.html#startup-initialization work for you?

> Second issue: No tutorial or documentation mentions that int main() is already provided.

From the page linked above:

![image](https://user-images.githubusercontent.com/3372458/46291403-3657bb00-c543-11e8-91b3-5b10430b6143.png)

**Comment by fwsGonzo** [comment]
Thanks, and yes I have gotten very far now. I used a static bool to just initialize the userspace portion once. And now I'm generating raw packets.

I am having trouble because it's very rarely generating IP packets with correct checksums. Should I just go one level up and checksum the data libfuzzer is giving me myself? To help it along.

**Comment by Dor1s** [comment]
Yep, either provide correct checksums or disable it, also see http://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode
