### ISSUE TITLE
Fuzzing IP stack

### ISSUE THREAD

**Issue by fwsGonzo** [google/fuzzer-test-suite#130]
I'm currently fuzzing an IP stack written in modern C++, and I recently added a way to "apply" payloads. Only one payload is not always enough to trigger the crash, so I was wondering what your thoughts are on this? What if the fuzzer could dump the last X payloads?

Example:
```
 +--> WARNiNG: Environment unsafe for production
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [ Network ] Creating stack for UserNet on eth0 (MTU=4000)
       [ Inet ] Bringing up eth0 on CPU 0
       [ Inet ] Network configured (01:02:03:04:05:06)
                IP: 		10.0.0.42
                Netmask: 	255.255.255.0
                Gateway: 	10.0.0.1
                DNS Server: 	10.0.0.1
    [ Network ] Creating stack for UserNet on eth1 (MTU=4000)
       [ Inet ] Bringing up eth1 on CPU 0
       [ Inet ] Network configured (01:02:03:04:05:06)
                IP: 		10.0.0.43
                Netmask: 	255.255.255.0
                Gateway: 	10.0.0.1
                DNS Server: 	10.0.0.1
*** Inserting payload crash-ac14c3b630c779e70d5e47363ca5d48842c9704f into stack...
ip4: Ignored checksum on packet
*** Payload crash-ac14c3b630c779e70d5e47363ca5d48842c9704f was inserted into stack
```
Not crashing!

**Comment by kcc** [comment]
The typical recommendations for fuzzing a target that consumes N payloads
is to split the input of `LLVMFuzzerTestOneInput` into N chunks and treat them as N payloads. 

The question is how exactly to split the input. 

One way is to e.g. dedicate first byte to store N, then the next N or 2*N bytes to store
the sizes of payloads, then put the payloads. 

Another, much more powerful but also heavyweight approach is to wrap the array of payloads 
into a protobuf and use https://github.com/google/libprotobuf-mutator  with libFuzzer

You clearly want to have a seed corpus of such inputs collected from e.g. real loads or existing tests. 

BTW, this project is not the best place to ask questions like this. 
libfuzzer@googlegroups.com is better.

**Comment by fwsGonzo** [comment]
You are right in that, however I had one idea. The fuzzer does know when it reaches a new area, or modifies some state. In the TCP overall there isn't much state. So, the last N (or even all) payloads that modified state could be replayed by having the fuzzer dump them all at the end.

Is that not a viable idea?

**Comment by kcc** [comment]
> The fuzzer does know when it reaches a new area

yes

> or modifies some state

Hmm. Not necessary. 

> having the fuzzer dump them all at the end.

you can achieve that with libprotobuf-mutator
