### ISSUE TITLE
does providing LLVMFuzzerCustomMutator stop other mutations?

### ISSUE THREAD

**Issue by luxe** [google/fuzzer-test-suite#134]
If I implement `LLVMFuzzerCustomMutator` will libfuzzer still perform all of the same standard mutations as before? Or does implementing this function cancel all the other mutations and it only runs the implementation given?

**Comment by luxe** [comment]
looks like it gets added to the existing mutations:  
http://llvm.org/doxygen/FuzzerMutate_8cpp_source.html#l50

**Comment by kcc** [comment]
If you have `LLVMFuzzerCustomMutator` it will be the only mutator called by libFuzzer. 
But inside your `LLVMFuzzerCustomMutator` you may call `LLVMFuzzerMutate` on a subset of data, 
which will in turn call all existing libFuzzer mutators.

**Comment by luxe** [comment]
Thanks.  I want my mutator to be called as frequently as the other mutators.  
So here is what I do:

```
extern "C" size_t LLVMFuzzerCustomMutator(uint8_t *Data, size_t Size, size_t MaxSize, unsigned int Seed)
{
    const size_t                          NUMBER_OF_INTERNAL_MUTATORS = 13;
    std::mt19937                          engine{Seed};
    std::uniform_int_distribution<size_t> dist(0, NUMBER_OF_INTERNAL_MUTATORS);
    auto                                  do_custom = dist(engine);
    if (do_custom == 0)
    {
        return MyMutate(Data, Size, MaxSize, Seed);
    }

    return LLVMFuzzerMutate(Data, Size, MaxSize);
}
```

**Comment by kcc** [comment]
That's a bad idea IMHO. 
you make the fuzz target non-deterministic (and we ask not to do this: http://llvm.org/docs/LibFuzzer.html#id22). 
It could be much better to have two fuzzer builds, one w/ and one w/o the custom mutator, 
and let them share the corpus.

**Comment by luxe** [comment]
I see. Two builds make sense.
Do you think we could add a hook one day to insert custom mutators into the framework and still be overall deterministic?  And by that I mean, I want to seamlessly add more mutators to run alongside the existing ones.

**Comment by kcc** [comment]
Maybe, but I have no such plans currently.

**Comment by occia** [comment]
> Thanks. I want my mutator to be called as frequently as the other mutators. So here is what I do:
> 
> ```
> extern "C" size_t LLVMFuzzerCustomMutator(uint8_t *Data, size_t Size, size_t MaxSize, unsigned int Seed)
> {
>     const size_t                          ` = 13;
>     std::mt19937                          engine{Seed};
>     std::uniform_int_distribution<size_t> dist(0, NUMBER_OF_INTERNAL_MUTATORS);
>     auto                                  do_custom = dist(engine);
>     if (do_custom == 0)
>     {
>         return MyMutate(Data, Size, MaxSize, Seed);
>     }
> 
>     return LLVMFuzzerMutate(Data, Size, MaxSize);
> }
> ```

May I further check why this implementation is non-deterministic? The `do_custom` will always be the same value if given the same `Seed` (assume `NUMBER_OF_INTERNAL_MUTATORS` is not changed).
Besides, in the google provided custom mutator [example](https://github.com/google/fuzzing/blob/master/docs/structure-aware-fuzzing.md#example-png), it uses a [similar approach](https://github.com/google/fuzzer-test-suite/blob/6955fc97efedfda7dcc0979658b169d7eeb5ccd6/libpng-1.2.56/png_mutator.h#L117) to create the custom PNG mutator.
