### ISSUE TITLE
 Fuzzing the JIT compiler of V8

### ISSUE THREAD

**Issue by pratikbhd** [google/fuzzer-test-suite#135]
Hello,
I am currently working on a project that involves fuzzing JIT compilers. I am looking into libFuzzer and was trying to figure out how I can use libFuzzer to fuzz the JIT compiler engines of V8. I could not find any tutorials or documentation that talked about integrating libFuzzer with V8 and JIT compilers in specific.

I was wondering if there are any resources I can look into to understand how I can use **libFuzzer** (or any other fuzzer such as **oss-fuzz** or **jfs**) to fuzz the JIT compilers of V8.

Thanks!

**Comment by kcc** [comment]
Sorry, this is a wrong place to ask about V8 fuzzing. 
You probably want to look here: https://github.com/v8/v8/tree/master/test/fuzzer
