### ISSUE TITLE
How much memory is recommended/required for the test suite?

### ISSUE THREAD

**Issue by benedikt90** [google/fuzzer-test-suite#141]
Running into a lot of `AddressSanitizer: allocator is out of memory trying to allocate 0x1000 bytes` and `ERROR: Failed to mmap` errors and I'm wondering if it is the compilation or the machine. I'm using a 2GB no SWAP and 1 vCore cloud instance. What would you recommend?

**Comment by morehouse** [comment]
My guess is too little RAM on the machine.  The tutorial has been written and tested with Google Cloud, which I believe defaults to 3.75 GB per vCPU.  I'd suggest trying that and reporting back if that doesn't solve your issue.
