### ISSUE TITLE
evaluate libFuzzer's -fork=1 mode

### ISSUE THREAD

**Issue by kcc** [google/fuzzer-test-suite#142]
Matt, please try to evaluate `-fork=0` (default) vs `-fork=1` using the fresh clang

**Comment by morehouse** [comment]
- [24 hour A/B test of `-fork=0` vs `-fork=1`, most benchmarks  ](https://storage.googleapis.com/fuzzer-test-suite-public/fork-mode/index.html)
- [50 hour A/B test of `-fork=0` vs `-fork=1`, vorbis only](https://storage.googleapis.com/fuzzer-test-suite-public/fork-vorbis/index.html)

In general fork modes seems to start off much slower than the normal mode, but catches up and wins for benchmarks that crash a lot (e.g., pcre2), while significantly lagging behind for less buggy benchmarks.
