### ISSUE TITLE
Help to understand libFuzzer

### ISSUE THREAD

**Issue by saarshah** [google/fuzzer-test-suite#154]
Hi, I am totally new to fuzzing and also to libFuzzer. I have successfully setup and run this tutorial and seen desired outputs. But I want to know the internal working, especially the how to generate data and its size and then give these arguments to our function under test. 
```
bool FuzzMe(const uint8_t *Data, size_t DataSize) {
  return DataSize >= 3 &&
      Data[0] == 'F' &&
      Data[1] == 'U' &&
      Data[2] == 'Z' &&
      Data[3] == 'Z';  // :‑<
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
  FuzzMe(Data, Size);
  return 0;
}
```

1. So how (and what ) the values for Data pointer and Size are generated ? 
2. in FuzzMe function, we are checking that DataSize should be >= (greater than or equal to) 3. In this it should not be a bug, because it also valid >3... why its a bug at Data[3]='Z' ?

**Comment by kcc** [comment]
1. You can think of `Data` and `Size` as randomly generated values. Of course, they are much better than just random.  A great paper that explains the concept of coverage-guided fuzzing is https://patricegodefroid.github.io/public_psfiles/ndss2008.pdf
2. If `DataSize==3`, the check `DataSize >= 3` will pass, and `Data[3]` will read out of bounds.

**Comment by saarshah** [comment]
thanks for recommended paper and explanation.. One more help, if we want to fuzz large codebase of blockchain projects (means containing lot of files, folders, modules,  libraries, Hashes, network protocol, etc.)  How could then we utilize this fuzzer (in order how to configure it, generate test cases, and fuzz)

**Comment by kcc** [comment]
Sorry, your question is very vague. 
If you want to see how libFuzzer is used in a huge software project, take a look at 
https://chromium.googlesource.com/chromium/src/+/master/testing/libfuzzer/README.md
