### ISSUE TITLE
Can I add my own fuzzers to compare?

### ISSUE THREAD

**Issue by AIK13** [google/fuzzer-test-suite#169]
I see that AFL, Libfuzzer and Libfuzzer's FsanitizeFuzzer are supported. Does this mean that if I write a config file that sets the engine to Hongfuzz, for example, I won't be able to run it because there's no support?

Basically, my question is: does the config file only recognize AFL and Libfuzzer as valid engines?

**Comment by morehouse** [comment]
Honggfuzz is not currently supported, though it could be added.

I'd suggest taking a look at https://github.com/google/fuzzbench, since it is still being actively developed and already supports honggfuzz.
