### ISSUE TITLE
About original seeds

### ISSUE THREAD

**Issue by VulnerabilityAnalyzer** [google/fuzzer-test-suite#170]
I noticed that that some programs has original input seeds such as boringssl.
But there are some programs that do not have original seeds like re2.
Would you help to produce some seeds as the original input?

**Comment by morehouse** [comment]
Fuzzers can run with or without seed inputs.  Some of the benchmarks here have them, some don't.

Adding seed inputs to benchmarks that currently don't have them would likely change the bugs and coverage found by the benchmark.  Unless we have a good reason to, I'd prefer to leave them without seed inputs.

**Comment by VulnerabilityAnalyzer** [comment]
Thank you.
