### ISSUE TITLE
Have runners execute on dedicated cores

### ISSUE THREAD

**Issue by morehouse** [google/fuzzer-test-suite#64]
We would like to minimize the impact of runner bookkeeping operations (copying corpus, rsync, etc.) on fuzzing times.  One way to approach this is to limit fuzzing to a dedicated VM core and use the other core for bookkeeping operations.

Assigning to David for now, but it's probably more important for him to get an end-to-end system running before he leaves.

**Comment by dnoursi** [comment]
I've done maybe a dozen experiments so far, but I've found very few benchmarks which manage to even finish one trial in reasonable time on an `n1-standard-1` single core machine. This is highly suspect, given that these are benchmark which we expect to finish in 5~10 minutes.

By contrast, two core `n1-standard-2` machines finish benchmarks in a more reasonable time, so I'm using them for now in my experiments. I'm still hoping to investigate this further

**Comment by morehouse** [comment]
>This is highly suspect, given that these are benchmark which we expect to finish in 5~10 minutes. 

This isn't too surprising since we run with `-workers=8` but the VMs have less than 8 cores.

**Comment by morehouse** [comment]
Have had dual-core runners for a while now.  One core is used for fuzzing while the other is used for bookkeeping.
